services:
  nextflow-api:
    image: nextflow-api
    build: .
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - ${DATA_DIR}:${DATA_DIR}
      - ${PIPELINE_DIR}:${PIPELINE_DIR}
    environment:
      PIPELINE_PATH: "${PIPELINE_DIR}/main.nf"
      RUN_DIR: ${DATA_DIR}/runs
      DB_PATH: ${DATA_DIR}/runs.db
      NEXTFLOW_BIN: nextflow
      JWT_SECRET: ${JWT_SECRET}
      CONSUL_ENABLED: false
      CONSUL_BASE_URL: http://consul:8500
      CONSUL_TOKEN: ${CONSUL_TOKEN}
      CONSUL_SERVICE_ID: NextflowApi.${CI_ENVIRONMENT_NAME}
      CONSUL_SERVICE_NAME: NextflowApi
      CONSUL_SERVICE_API_URL: nextflow-api
      CONSUL_SERVICE_API_PORT: 8000
    restart: unless-stopped
