services:
  nextflow-api:
    image: nextflow-api
    build: .
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - ${DATA_DIR}:${DATA_DIR}
      - ${PIPELINE_DIR}:${PIPELINE_DIR}
    environment:
      PIPELINE_PATH: "${PIPELINE_DIR}/main.nf"
      RUN_DIR: ${DATA_DIR}/runs
      DB_PATH: ${DATA_DIR}/runs.db
      NEXTFLOW_BIN: nextflow
    restart: unless-stopped
